### ISSUE TITLE
fix(ecosystem): add multi-platform tags to crate.iced

### ISSUE THREAD

**Issue by gacallea** [areweguiyet/areweguiyet#164]
Hi :)

first things first: thanks for this effort and amazing site.

## Issue:

As of today, [Iced](https://iced.rs) has no tags at all. This can be confusing when searching by OS. In my case I was looking for macOS but Iced didn't pop up in the results. I had to check a Rust app I use to see what they used.

## Solution

Libraries such as Iced, which is multi-platform (Windows, macOS, Linux, and the Web), should be tagged accordingly. Including any platform they cover.

## PR

I'd be more than happy to contribute to this issue with a PR if you could confirm if the following is correct.

Note: I have no clue about `winit` and `winapi`. I am unsure what does Iced target.
Note: `linux` would be nice to have as tag. I am unsure what does Iced target.
Note: I am unsure what to add for `Web`

```toml
# just an idea
[crate.iced]
name = "Iced"
description = "A renderer-agnostic GUI library for Rust focused on simplicity and type-safety. Inspired by Elm."
tags = [
  "winapi",
  "macos",
  "linux"
 ]
```
